import {UserLdap} from './user-ldap'

// Remplit les données de la BDD présente dans user-ldap.ts
// Mock permet de faire semblant d'appeler un webservice

export const LDAP_USERS: UserLdap[] = [
  {
    login: 'test.v1',
    nom: 'V1',
    prenom: 'Test',
    nomComplet: 'V1 Test',
    motDePasse: null,
    mail: 'test.v1@epsi.fr',
    role: 'ROLE_USER',
    employeNumero: 1234,
    employeNiveau: 120,
    dateEmbauche: '2020-01-01',
    publishedId: 1,
    active: true,
  },
  {
    login: 'test.v2',
    nom: 'V2',
    prenom: 'Test',
    nomComplet: 'V2 Test',
    motDePasse: null,
    mail: 'test.v2@epsi.fr',
    role: 'ROLE_USER',
    employeNumero: 2345,
    employeNiveau: 220,
    dateEmbauche: '2020-02-02',
    publishedId: 2,
    active: true,
  },
  {
    login: 'test.v3',
    nom: 'V3',
    prenom: 'Test',
    nomComplet: 'V3 Test',
    motDePasse: null,
    mail: 'test.v3@epsi.fr',
    role: 'ROLE_USER',
    employeNumero: 3456,
    employeNiveau: 330,
    dateEmbauche: '2020-03-03',
    publishedId: 3,
    active: false,
  },
  {
    login: 'test.v4',
    nom: 'V4',
    prenom: 'Test',
    nomComplet: 'V4 Test',
    motDePasse: null,
    mail: 'test.v4@epsi.fr',
    role: 'ROLE_USER',
    employeNumero: 4567,
    employeNiveau: 440,
    dateEmbauche: '2020-04-04',
    publishedId: 4,
    active: true,
  },
  {
    login: 'test.v5',
    nom: 'V5',
    prenom: 'Test',
    nomComplet: 'V5 Test',
    motDePasse: null,
    mail: 'test.v5@epsi.fr',
    role: 'ROLE_USER',
    employeNumero: 5678,
    employeNiveau: 110,
    dateEmbauche: '2020-05-05',
    publishedId: 5,
    active: true,
  },
];
